SELECT * FROM PROFESSOR;
-- 1. BONUS를 받는 교수들만 출력
-- 2. 급여가 300~400 사이인 교수들 출력
-- 3. ID에 'a'가 들어가는 교수 출력
-- 4. PROFNO, NAME, ID를 임의로 넣어서 교수 레코드 INSERT
-- 5. 4번에서 만든 데이터 DELETE
-- 6. 급여가 300이하인 교수들의 급여를 +10 UPDATE

-- 1)
SELECT * FROM PROFESSOR WHERE BONUS IS NOT NULL;
-- 2)
SELECT * FROM PROFESSOR
WHERE PAY BETWEEN 300 AND 400;
-- 3)
SELECT * FROM PROFESSOR
WHERE ID LIKE '%a%';
-- 4)
INSERT INTO PROFESSOR(PROFNO, NAME, ID)
VALUES('4008', '망나뇽', 'asdqq0');
-- 5)
DELETE FROM PROFESSOR WHERE PROFNO = '4008';
-- 6)
UPDATE PROFESSOR SET 
PAY = PAY + 10 
WHERE PAY <= 300;

SELECT * FROM PROFESSOR;


