-- SELECT / INSERT / UPDATE / DELETE --

SELECT * 
FROM STUDENT;
-- SELECT * FROM STUDENT;

SELECT STU_NO, STU_NAME 
FROM STUDENT;
-- SELECT STU_NO, STU_NAME FROM STUDENT;

SELECT SUBSTR(STU_NAME, 2, 2)
FROM STUDENT;
-- SELECT SUBSTR(STU_NAME, 2, 2) FROM STUDENT;

SELECT * 
FROM STUDENT
WHERE STU_GENDER = 'M';
-- SELECT * FROM STUDENT WHERE STU_GENDER = 'M';

SELECT * 
FROM STUDENT
WHERE STU_GENDER = 'M' AND STU_DEPT = '전기전자';
-- SELECT * FROM STUDENT WHERE STU_GENDER = 'M' AND STU_DEPT = '전기전자';

SELECT * 
FROM STUDENT
WHERE STU_HEIGHT >= 170;
--SELECT * FROM STUDENT WHERE STU_HEIGHT >= 170;

SELECT * 
FROM STUDENT
WHERE STU_HEIGHT IS NULL; -- IS NOT NULL
-- SELECT * FROM STUDENT WHERE STU_HEIGHT IS NULL; / IS NOT NULL

SELECT *
FROM STUDENT
WHERE SUBSTR(STU_NO, 3, 2) = 15;
-- SELECT *FROM STUDENT WHERE SUBSTR(STU_NO, 3, 2) = 15;

SELECT *
FROM STUDENT
ORDER BY STU_HEIGHT DESC; -- ASC 오름차순 / DESC 내림차순
-- SELECT *FROM STUDENT ORDER BY STU_HEIGHT DESC;

SELECT *
FROM STUDENT
ORDER BY STU_GRADE, STU_CLASS;
-- 문법 : 조건 WHERE 후에 정렬 ORDER BY

SELECT *
FROM STUDENT
WHERE STU_GENDER = 'M'
ORDER BY STU_HEIGHT;

SELECT STU_NO AS "학생 번호", STU_NAME AS 이름, STU_DEPT 학과
FROM STUDENT; -- 별칭을 줄땐 AS와 ""생략가능!

SELECT * FROM STUDENT;
-- SELECT * FROM STUDENT WHERE STU_HEIGHT >= 165 AND STU_HEIGHT <= 175;
-- 키가 165 ~ 175 사이의 학생들
SELECT * 
FROM STUDENT 
WHERE STU_HEIGHT BETWEEN 165 AND 175;
-- BETWEEN 사용으로 특정 사이값 구하기

SELECT * 
FROM PROFESSOR
WHERE POSITION IN ('정교수','조교수');
-- WHERE POSITION = '정교수' OR POSITION = '조교수';
-- POSITION이 정교수이거나 조교수인것

SELECT * 
FROM PROFESSOR
WHERE POSITION LIKE '%교수%';
-- POSITION 안에 앞뒤로 어떤 글자가 와도 상관없고, 교수가 들어가면 출력
-- 교수% => 교수라는 단어로 시작
-- %교수 => 교수라는 단어로 끝
------------------------------------------------------

