-- 셀프 조인 (SELF JOIN)
SELECT * FROM EMP;

SELECT E1.EMPNO, E1.ENAME, E2.ENAME AS MANAGER
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;

--
SELECT *
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO;
SELECT * FROM PROFESSOR;


SELECT PROFNO, NAME, D1.DNAME, D2.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO;