--- OUTER JOIN(LEFT, FRIGHT) ---
SELECT * FROM PROFESSOR;
SELECT * FROM STU;

SELECT P.NAME, P.POSITION, NVL(S.NAME, '담당학생없음')
FROM PROFESSOR P
LEFT JOIN STU S ON P.PROFNO = S.PROFNO;

-- 학번, 학생이름, 담당교수 이름 출력
-- 담당 교수가 없으면 '없음'으로 출력
SELECT STUNO, S.NAME, NVL(P.NAME, '담당교수없음') 담당교수
FROM STU S
LEFT JOIN PROFESSOR P ON S.PROFNO = P.PROFNO;

--NVL(TO_CHAR(AVG(ENR_GRADE)), '점수 없음')

SELECT STU_NAME, COUNT(ENR_GRADE)
FROM STUDENT S 
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;

-- EMP
-- 부하직원의 수를 구하고 싶다 없으면 0으로 출력
-- 사번, 이름, 자신의 부하직원 수 
SELECT * FROM EMP;
SELECT E.EMPNO, E.ENAME, COUNT(E2.MGR)
FROM EMP E
LEFT JOIN EMP E2 ON E.EMPNO = E2.MGR
GROUP BY E.EMPNO, E.ENAME;

--
SELECT MGR, COUNT(*)
FROM EMP
WHERE MGR IS NOT NULL
GROUP BY MGR;

SELECT EMPNO, ENAME, NVL(CNT, 0) AS CNT
FROM EMP E
LEFT JOIN (
    SELECT MGR, COUNT(*) AS CNT
    FROM EMP
    WHERE MGR IS NOT NULL
    GROUP BY MGR
) T ON T.MGR = E.EMPNO
ORDER BY CNT DESC;
